# Generated by Django 5.0.1 on 2024-01-15 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_remove_item_reviews'),
        ('reviews', '0002_remove_review_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='items.item'),
            preserve_default=False,
        ),
    ]
