# Generated by Django 5.0.1 on 2024-01-15 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='reviews',
        ),
    ]
