# Generated by Django 5.0.1 on 2024-01-15 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorys', '0001_initial'),
        ('items', '0004_remove_item_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='categorys.category'),
            preserve_default=False,
        ),
    ]
